version: '3.9'

services:
  stage-dbms:
    image: mariadb
    restart: always
    ports:
      - "3310:3306"
    env_file: 
      - ./dbms/.env.stage
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
    ]
    volumes:
      - ./stage/dbms/dbms-data:/var/lib/mysql
      - ./dbms/mariadb.cnf:/etc/mysql/mariadb.cnf
      # Pointer vers un dossier qui aura des scripts d'initialisation de notre base
      - ./dbms/stage-initdb.d:/docker-entrypoint-initdb.d
      # Ajouter le DDL qui va tourner en dernier
      - ./dbms/ddl/ddl.sql:/docker-entrypoint-initdb.d/999-ddl.sql
    networks:
      - api-stage-network
    labels:
      co.elastic.logs/enabled: false
   

  stage-api:
    build: 
      context: ./
      dockerfile: ./Dockerfile.prod
    container_name: api
    ports:
      - "5060:5050"
    environment:
      - NODE_ENV=prod
      - PORT=5050
      - DB_HOST=stage-dbms
      - DB_USER=api-stage
      - DB_PASSWORD=api-stage-password
      - DB_DATABASE=mtdb_stage
      - REFRESH_TOKEN_SECRET=7400699ee7d9b2f99c65fddc6011c9323cb8b87d92b6d6355a10bf17d14f18ee43522b7a52a655ae7e945a8c160939b9f6e1153ca15e3bf8fa8156a7f54da1e8
      - ACCESS_TOKEN_SECRET=eaf69e4a9e8c7ff5175e78ddd1b0a6699de7715166d7d449a47acdf538b201222a1767919b9c91688db66e0ed299c5758d226d3c620c46099212860c8ee648ef
      - MJ_APIKEY_PUBLIC=23c6c983ac1fabd14a0337ba32b28a8c
      - MJ_APIKEY_PRIVATE=cbd678702d44ebe413aeac3a50b4b3b7
      - MAIL_TO_CHALLENGE=a_parent1@hetic.eu     
      - AWS_ACCESS_KEY_ID=SCWTY6B680E3QQ9WM2V5
      - AWS_SECRET_ACCESS_KEY=18856bfe-8260-4cfd-8802-389f943deccf
      - STORAGE_REGION=fr-par
      - STORAGE_ENDPOINT=https://s3.fr-par.scw.cloud
      - STORAGE_BUCKET=object-storage-playground
    networks:
      - api-stage-network
    restart: always
    depends_on:
      - stage-dbms
    labels:
      co.elastic.logs/processors.1.add_fields.fields.logging_container: "stage-api"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"


networks:
  api-stage-network:
    driver: bridge
